#DB dev specific
spring.datasource.url=jdbc:sqlserver://;serverName=DSER-LIS.infra.karnataka.gov.in;databaseName=sericultureprd;encrypt=true;trustServerCertificate=true;
spring.datasource.username=seruser1
spring.datasource.password=Seri01@07user1
#otp.sms.url=${SMS_CONFIGURE}
#otp.sms.username=${SMS_USERNAME}
#otp.sms.password=${SMS_PASSWORD}
#otp.sms.senderId=${SMS_SENDER_ID}
#otp.sms.secureKey=${SMS_SECURE_KEY}
#otp.sms.templateId=${SMS_TEMPLATE_ID}
otp.sms.url=http://65.2.76.193/index.php/sendmsg
otp.sms.username=Mobile_1-COMDOS
otp.sms.password=COMDOS@1234
otp.sms.senderId=COMDOS
otp.sms.secureKey=046bdec5-4bba-69b3-k4e4-01d6b555c9cv
otp.sms.templateId=1107170082061011792

spring.jpa.show-sql= false
# Custom Properties
# Please ensure you use right options just for dev feasibility everything is allowed, which will not be the case in production.
sericulture.cors.allowed-origins: "*"
sericulture.cors.allowed-methods: "*"
sericulture.cors.max-age: 3000
sericulture.cors.allowed-headers: "*"
sericulture.cors.xposed-headers: "*"
#DB dev specific
# spring.datasource.url=jdbc:sqlserver://;serverName=database-1.cog2zz2pbsge.ap-south-1.rds.amazonaws.com;databaseName=sericulture;encrypt=true;trustServerCertificate=true;
# spring.datasource.username=admin
# spring.datasource.password=$en0vg2023
#ADD THE DB PROPERTIES IN BASE APP
spring.main.allow-circular-references=true
#ROLE TO BE SAVED WHILE SAVING USERS, TO BE OVERWRITTEN IN BASE APP
app.rest.role=1
#JWT TOKEN WILL EXPIRE AFTER THIS MINUTES
jwt.expire.minutes=30000